version: '3'
services:
  wireguard_kr:
    image: sdlanti/wireguard_kr
    container_name: wireguard_kr
    environment:
      - PORT=51820
      - DNS=77.88.8.8, 8.8.8.8
      - QR_ENABLE=1
    volumes:
      - ~/wireguard/:/etc/wireguard/
    restart: always
    ports:
      - 51820:51820/udp
    cap_add:
      - SYS_MODULE
      - NET_ADMIN