version: '3.8'
services:
  wireguard:
    build: .
    image: wga1
    volumes:
      - /home/sd--anti/wireguard/123:/etc/wireguard/
    restart: allways
    ports:
      - 51820:51820/udp
    environment:
      - QR_ENABLE=1
      - PORT=51820
      - DNS="77.88.8.8, 8.8.8.8"
    
    cap_add:
      - SYS_MODULE
      - NET_ADMIN